application: leyaproject
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.app

libraries:
- name: django
  version: "latest"

env_variables:
  DJANGO_SETTINGS_MODULE: 'leyaproject.settings.settings'
  SECRET_KEY: 'django.secret.key.here'
